[project]
name = "hexlet-code"
version = "0.1.0"
description = "python-project-83"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[dependency-groups]
dev = [
    "ruff>=0.11.8",
]
